name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Test
        run: |
          ./gradlew check

      - name: Build
        run: |
          ./gradlew jsBrowserProductionWebpack

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build/distributions
