name: Test

on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Test
        run: |
          ./gradlew check
